version: '3.7'

services:
  app:
    build:
      context: ..
      args:
        - PORT=${PORT}
      dockerfile: ./docker/Dockerfile
      target: prod
    image: ${APP_NAME}:prod
    container_name: ${APP_NAME}
    restart: always
    environment:
      - TZ=${TZ}
    ports:
      - ${EXTERNAL_PORT}:${PORT}
